### PR TITLE
initial commit for release CD

### PR DESCRIPTION
**Pull request by bernt-matthias**
TODO: 

- [ ] switch to on: release (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)
- [ ] fix tensorflow base image to a version? i.e. 2.3.0-gpu instead of latest
- [ ] deploy the container somewhere
- [ ] add test task for container

### CODE REVIEW

**Comment by halirutan** [comment]
@bernt-matthias Your initial intention to install the `dfpl` directly from the source was a good one! You just missed one important point: You need to map the `deepFPlearn` directory into the container so that it has read access. To make it work, you'd just need fix the following thing in the singularity def file: [Here](https://github.com/yigbt/deepFPlearn/blob/master/singularity_container/conda_rdkit2019.def#L11) you remove the package again and put the file system mapping (source -> container destination) in. So since we're calling singularity from the `singularity_container` directory, it is

```
.. /deepFPlearn
```

The parent dir is mapped to `/deepFPlearn` in the container. Then we can do exactly what you initially had:

```
/bin/bash -c ". $CONDA_DIR/etc/profile.d/conda.sh; conda activate rdkit2019; python -m pip install /deepFPlearn"
```

**Comment by halirutan** [comment]
Alright, I pulled your branch, fixed the singularity built and created a new [feat_singularity_CD](https://github.com/yigbt/deepFPlearn/tree/feat_singularity_CD) branch with all additions on this repo.

@mai00fti Can we make Matt a developer of this repository so that we can work together on this?

**Comment by halirutan** [comment]
@bernt-matthias OK, check [here](https://github.com/yigbt/deepFPlearn/runs/1163241609?check_suite_focus=true#step:4:3154):

```
FATAL:   While performing build: 
while creating SIF: while creating container: writing data object for SIF file:
copying data object file to SIF file:
write /__w/deepFPlearn/deepFPlearn/singularity_container/deepFPlearn.sif: no space left on device
```

What now?

**Comment by mai00fti** [comment]
> @mai00fti Can we make Matt a developer of this repository so that we can work together on this?

done

**Comment by halirutan** [comment]
@bernt-matthias Let us close this PR and work together on https://github.com/yigbt/deepFPlearn/tree/feat_singularity_CD

**Comment by bernt-matthias** [comment]
I just took you commits into my branch. I would prefer to keep working on this PR and you push to the branch in my form. 

Because leaving the PR also gives us a means of communication.

**Comment by halirutan** [comment]
Yes, I understand. We open a new WIP PR. The big advantage is that we don't need to pull and push between repos. Give me a second.

**Comment by halirutan** [comment]
Here you go: https://github.com/yigbt/deepFPlearn/pull/2

**Pull request closed without merging**
